packages:
  - 'apps/*'

devDependencies:
  eslint: '^8.47.0'
  prettier: '^3.0.2'
  tsconfig: '*'
  turbo: 'latest'

scripts:
  build: 'turbo run build'
  dev: 'turbo run dev'
  start: 'turbo run start'
  lint: 'turbo run lint'
  format: 'prettier --write "**/*.{ts,tsx,md}"'